### ISSUE TITLE
[Issue] Asking for a PIN but the card is not initialized

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#1]
At first start, the app is asking for the PIN but for a brand new card, the setup is not done yet. 
You should update the pop up message to make it more clear - like "Create a PIN code" instead of "Enter the PIN code of your card".

First popup
![image](https://github.com/user-attachments/assets/fc46db23-a123-40cc-b4c5-2cb1ef795256)

Second popup
![image](https://github.com/user-attachments/assets/2ae70f91-5ebd-4c96-aa83-aba25abe4c7f)

The user should be able to setup the Seedkeeper through the app.

**Comment by Tech-Aware** [comment]
Hi @Bastien-Satochip,
commit f0604aa and commit 95fe2f3
Here the  link to the commit concerned : 
- https://github.com/Tech-Aware/seedkeeper-tool/commit/f0604aa17f04861c32a622935adcdfaa28bf7cca
- https://github.com/Tech-Aware/seedkeeper-tool/commit/95fe2f3be4d0bf2fa1e0499cfc7acf0e3aa04c94
