### ISSUE TITLE
[Issue] Generate passwords does not work

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#11]
![image](https://github.com/user-attachments/assets/57a0e15c-74b2-4cae-a163-64fcf3941656)
There is no generation. The "Save on card" button is not working.

**Comment by Tech-Aware** [comment]
Hi @Bastien-Satochip 

For this part i'm thinknig about which entry are force to provide by user to make all verification.
For example, could a user genrate a Login/password without url or label ?

**Comment by Bastien-Satochip** [comment]
Hey, 

The only mandatory field is the label. 
The Login or the URL fields are "optional". If you want you can insert the "optional" word (in small italic) within the text field? So the user will know that those two fields are not mandatory.

Thank you.

**Comment by Tech-Aware** [comment]
For the first i will put an obligation to label field it is the most important !
53dd1c2ccbc2a056e00001dae2cd33f7572094c9
