### ISSUE TITLE
[UI-Update] Secret details and delete button

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#12]
If I create a secret from the existing "Seedkeeper-Tool" app, I can see it on the list and check the Secret Details.

![image](https://github.com/user-attachments/assets/771fb82b-74c5-4747-a0a8-01383f4d67db)

But I can't click on "Show" - it does not display the password. (This specific password is allowed to be exporterd in plaintext).

And I would rather see the "Delete secret" button on the bottom of the screen rather than the top. 

![image](https://github.com/user-attachments/assets/9c941bc8-0a87-4736-8820-ea8295f7c693)

Like this: 
![image](https://github.com/user-attachments/assets/fbae95f1-1a29-45eb-a09b-e92dcb83d703)

**Comment by Tech-Aware** [comment]
Hey @Bastien-Satochip 
i update it in the same time than encryption/decryption of password
here you have 2f5b76a14aabc91de848f0e5edffbe3c78d23125, a68397039b0e47310945c2ecac733248c5da8807
