### ISSUE TITLE
[Add functionnality] Add the backup functionnality

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#14]
Add the backup option from one card to another.
Let's discuss it.

Voir Figma for UI.

**Comment by Tech-Aware** [comment]
@Bastien-Satochip 

All the UI is implemented as you can see in the following commit b3e6a397ab1cce9962c5228fa37834b6c860b0d1

You can see an example here : 

https://github.com/user-attachments/assets/9e6ed95e-fa5f-4265-a160-27e5e1b71716

**Comment by Tech-Aware** [comment]
Hi @Bastien-Satochip 
with a lot of pleasure and satisfactio, i offer you two commits : b737ca917e46b5ea741edfc863302dd09462f1d9, 08b16cc95d280fc68b4c6f5120c16ad4458346d5 corresponding to the implementation of the backup functionality.

See an example below:

https://github.com/user-attachments/assets/d170f795-dacf-4191-95e1-bb5330374a61
