### ISSUE TITLE
[UI-Update] Change the wordings "Couple login/password"

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#2]
To have something similar between the mobile app and the desktop app, could you change this: 
"Couple login/password"
into this: 
"Login/password"

![image](https://github.com/user-attachments/assets/8b049aa5-66ac-4e85-bc9b-778218ff24eb)

(In both "Generate" and "Import" screens)

**Comment by Tech-Aware** [comment]
Hi @Bastien-Satochip, 

this syntaxis problem is fixed https://github.com/Tech-Aware/seedkeeper-tool/commit/4643c8835c43806eeb57bf39cf782dfd70351762

**Comment by Tech-Aware** [comment]
Hi @Bastien-Satochip,

this syntaxis problem is fixed https://github.com/Tech-Aware/seedkeeper-tool/commit/4643c8835c43806eeb57bf39cf782dfd70351762
