### ISSUE TITLE
[UI-Update] Import a mnemonic - Pop up issue when no mnemonic is provided

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#21]
If you go to "Import" -> "Mnemonic seedphrase"
And you don't fill any field and click on "Save on card", you got the following pop up:

![image](https://github.com/user-attachments/assets/bf21d5df-8169-426d-8901-d7e6643278e1)

Please adapt it: 
- it should have the "Import" logo 
![image](https://github.com/user-attachments/assets/f2349660-43c3-4595-82fa-efb4ae34c647)
- And I don't know why there is a "023" inf front of the "No mnemonic provided". Please remove the 023.

**Comment by Tech-Aware** [comment]
@Bastien-Satochip: 
- Solved with issue #20
