### ISSUE TITLE
[UI-Update] Pop up saying "... for password encryption" is missleading

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#23]
Within the app, either on the Generate menu or the Import menu, if you don't provide a label and click on "Save on card", you have this pop-up: 

![image](https://github.com/user-attachments/assets/9098c3e0-f655-451f-a34f-e2c58581da2a)

The message is not clear. 

Could you change the text from "Please, provide a label for password encryption" to "The label field is mandatory".

**Comment by Tech-Aware** [comment]
@Bastien-Satochip 
solved with issues #22 #21 #19 #18
