### ISSUE TITLE
[Bug] My secrets - Parsing a "Password" type is not working

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#26]
In "My secrets", the password information is not parsed correctly.

![image](https://github.com/user-attachments/assets/09b4f33f-0281-4671-aab7-e73b94863289)

![image](https://github.com/user-attachments/assets/4a4998b6-917d-4e36-9001-952d48724a24)

The password is: CjXWshbYR47
The login is; 2665-as-abn
The URL is https://my.bank.com

**Comment by Tech-Aware** [comment]
https://github.com/user-attachments/assets/48f4aacc-ba93-4997-a1f7-159b9476e370

@Bastien-Satochip something very strange mentioned there ! 

As you can see, a password that is generated (and imported to) can be display correctly in my build version.

> In "My secrets", the password information is not parsed correctly.
> 
> ![image](https://private-user-images.githubusercontent.com/87421384/363694118-09b4f33f-0281-4671-aab7-e73b94863289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyODQ0NjQsIm5iZiI6MTcyNTI4NDE2NCwicGF0aCI6Ii84NzQyMTM4NC8zNjM2OTQxMTgtMDliNGYzM2YtMDI4MS00NjcxLWFhYjctZTczYjk0ODYzMjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEzMzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NDgwMmU2ODA1Zjc5OTEzY2FhNTAwZTM5YTYwMzQ0OGY1MjlmZGEzYTQ1ODE1ZTRhMmYwNjQzMDUyNWI0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iy1nrRaxOciV9pLgEVEI8C8L5uBtpetRHQ10bbzicKc)
> 
> ![image](https://private-user-images.githubusercontent.com/87421384/363694171-4a4998b6-917d-4e36-9001-952d48724a24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyODQ0NjQsIm5iZiI6MTcyNTI4NDE2NCwicGF0aCI6Ii84NzQyMTM4NC8zNjM2OTQxNzEtNGE0OTk4YjYtOTE3ZC00ZTM2LTkwMDEtOTUyZDQ4NzI0YTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEzMzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZWVkYmQwNDczNDhmMjJkZjRkMWIzOWMzNGY1ZDhjZmU0ZjMwZGE2Y2RiNzg0MmYyZmZlYmIwNzljYmZjODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jl5ufsnq5VIFpNw9eoOnAgnQJk_pZ4z4YeLTvTjstzA)
> 
> The password is: CjXWshbYR4 The login is; 2665-as-abn The URL is https://my.bank.com

**Comment by Bastien-Satochip** [comment]
Indeed, when you import a secret using the desktop app, there is no problem. 
But when you:
- 1) Import a password using the Android mobile app
- 2) Try to read it from the desktop app

You encounter the issue I explained here.

Maybe @Toporin can help us?

**Comment by Tech-Aware** [comment]
@log_method
    def decode_secret_password(self, secret_hex):
        try:
            logger.info("001 Starting secret decoding process")

            # Convertir la chaîne hexadécimale en bytes
            secret_bytes = binascii.unhexlify(secret_hex)


            # Décoder en UTF-8
            decoded_secret = secret_bytes.decode('utf-8')

            # Initialiser le dictionnaire de résultats
            result = {
                'password': '',
                'login': '',
                'url': ''
            }

            # Séparer les parties
            parts = decoded_secret.split('login:')

            if len(parts) > 1:
                # Le mot de passe est la première partie
                result['password'] = parts[0].strip()

                # Traiter le reste
                remaining = parts[1]
                login_url_parts = remaining.split('url:')

                if len(login_url_parts) > 1:
                    result['login'] = login_url_parts[0].strip()
                    result['url'] = login_url_parts[1].strip()
                else:
                    result['login'] = remaining.strip()
            else:
                # Si 'login:' n'est pas trouvé, considérer tout comme mot de passe
                result['password'] = decoded_secret

            # Remplacer 'None' par une chaîne vide
            for key in result:
                if result[key] == 'None':
                    result[key] = ''

            logger.info("002 Secret successfully decoded")
            return result

        except binascii.Error as e:
            logger.error(f"003 Error decoding hex string: {str(e)}")
            raise ValueError("Invalid hexadecimal string") from e
        except Exception as e:
            logger.error(f"004 Unexpected error during secret decoding: {str(e)}")
            raise ControllerError(f"Failed to decode secret: {str(e)}") from e

**Comment by Bastien-Satochip** [comment]
Still not working.

![image](https://github.com/user-attachments/assets/1aed62f7-7067-4deb-b258-5235ab39a9fd)


Here is an example for a V1 card with a password with:
- a label called: PWD-Android
- no login
- no URL
- and a password: 4L8WLA9FEFJ

Here is the password output: 4L8WLA9FEFJLoginURL
