### ISSUE TITLE
[Bug] My secrets - Parsing a "BIP39 mnemonic" type is not working

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#27]
In "My secrets", the BIP39 mnemonic information is not parsed correctly.

![image](https://github.com/user-attachments/assets/cb3c717d-97a9-4746-802a-6c9251d0f4b2)

![image](https://github.com/user-attachments/assets/db3901b8-104d-454f-b07f-acca702a15b2)

BIP type is: BIP39
Label is : "Rabby Hot Wallet"
Seedphrase is : beyond kitchen ice crouch drift tilt bundle capable ghost client brand fence auto winter drill labor industry slender fire produce best security senior either
Passphrase is : passphrase

**Comment by Tech-Aware** [comment]
Hey @Bastien-Satochip 
Are we talking about this ?
![image](https://github.com/user-attachments/assets/cfb1f903-347e-491a-8779-acd955e76340)

If yes, it is normal that you cant read some masterseed cause i only implement for 16 byte and 32 bytes


According to the table attached, i will create a masterseed of each one to implement the retrieving of any masterseed mnemonic. 

It's what is need true ? 


> In "My secrets", the BIP39 mnemonic information is not parsed correctly.
> 
> ![image](https://private-user-images.githubusercontent.com/87421384/363694852-cb3c717d-97a9-4746-802a-6c9251d0f4b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE1MzIsIm5iZiI6MTcyNTM0MTIzMiwicGF0aCI6Ii84NzQyMTM4NC8zNjM2OTQ4NTItY2IzYzcxN2QtOTdhOS00NzQ2LTgwMmEtNmM5MjUxZDBmNGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MjcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjN2VlODZkYTVmZDQ2ZDI4ZmUyYzQ5ODY5NzZjMzNlMGUzZjI0MzU4MTk0MzJjMDRiMjk3NzM1YzQ0OWU1MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dFOWPM_rA8cJ7k_YIQXgbbjqyXZrH2T6KfvLuCk7rPw)
> 
> ![image](https://private-user-images.githubusercontent.com/87421384/363694881-db3901b8-104d-454f-b07f-acca702a15b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDE1MzIsIm5iZiI6MTcyNTM0MTIzMiwicGF0aCI6Ii84NzQyMTM4NC8zNjM2OTQ4ODEtZGIzOTAxYjgtMTA0ZC00NTRmLWIwN2YtYWNjYTcwMmExNWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA1MjcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYTBhZDc4ODA0MjhiM2U5ZTg3YTBiNGM2NDc1MGQ5NDE5YzdiMThkOGY0MDRiZmY5OTM2NjVmYTBkOGIyYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OXRVDSpZPW_az9lPIZYruSfyQtFHn5_wR_KdHVyzU_Q)
> 
> BIP type is: BIP39 Label is : "Rabby Hot Wallet" Seedphrase is : beyond kitchen ice crouch drift tilt bundle capable ghost client brand fence auto winter drill labor industry slender fire produce best security senior either Passphrase is : passphrase

**Comment by Tech-Aware** [comment]
@Bastien-Satochip

Here you have the commit https://github.com/Tech-Aware/seedkeeper-tool/commit/e75b9b1f1a9c9c84c7f912445de0b61e264bb665, https://github.com/Tech-Aware/seedkeeper-tool/commit/da782ddcec99ae7ee4b7d1dbc5c0a7a1ad8e3b73

https://github.com/user-attachments/assets/f12020cc-d909-4c3c-9183-a84d1d67681a

**Comment by Bastien-Satochip** [comment]
Working well.
