### ISSUE TITLE
[UI-Update] Help button not working

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#3]
As a reminder... 
The help button is not working.

**Comment by Tech-Aware** [comment]
> As a reminder... The help button is not working.

Yeah it's true, i was thinking about that could be better to put it on the settings, what do you feel about it @Bastien-Satochip ?

**Comment by Bastien-Satochip** [comment]
I would leave it on the main menu. It's more intuitive for the end-user to have the help menu visible directly.

**Comment by Tech-Aware** [comment]
Hi @Bastien-Satochip 
I update this part and now it's functional, you will be test it when i'll make .exe
here you have the commi's concerned : 
- b0fb3ace6e0be40874e49f6fc06e3a908bbd2a43
- 91943f81b02ea693cf03492eb713973f851caaa3
