### ISSUE TITLE
[Add functionnality] New secret type: 0xc0 - Free text

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#30]
We have add a new type of secret: free text. 
Meaning the user is allowed to insert some random data - aka free text - and save it to the secure element.

The type is: 0xc0

Could you add this type on the application ? 

In the "IMPORT" page, add in the selection: 
- Free text

And create the appropriate view to import some free text:
- The label
- A title: Free text to import:
- And the box where the user can past its data 

Something like this:

![image](https://github.com/user-attachments/assets/6d31a9cf-6fa9-4638-9164-2747e98afbe0)

**Comment by Tech-Aware** [comment]
Implemented for free/text : dcda1ea7123a15d2dd6790d9bf91c3ff0520ff8a, d7a2f46eeb139e1e510e750f641e6f1d21e6bb04
https://github.com/user-attachments/assets/4bdd0453-03ac-4b52-9edc-c937592e7871

**Comment by Bastien-Satochip** [comment]
Working well.
