### ISSUE TITLE
[UI-Update] My secrets - Upgrade the Secret details for type 0xc0 and 0xc1

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#32]
Knowing these issues, please update the "My secrets" - "Secret details" page accordingly to display those secret correctly.

![image](https://github.com/user-attachments/assets/8aa9b2e2-33fa-45a6-817e-00d1cff737e0)

- #30 https://github.com/Tech-Aware/seedkeeper-tool/issues/30
- #31 https://github.com/Tech-Aware/seedkeeper-tool/issues/31

**Comment by Tech-Aware** [comment]
here you have @Bastien-Satochip : ba90cd1621a82eb63ea4503e6cd93cba72d53f20, d8d2636811b68965982709b19b0796761b2f7b5b


https://github.com/user-attachments/assets/4828e28f-adac-4dcd-a0ba-35f38c2a0e54

**Comment by Tech-Aware** [comment]
66b4d084fc0650678a9e98dac8cc06dc013ed9b0

**Comment by Bastien-Satochip** [comment]
Parfait, merci.
