### ISSUE TITLE
[Bug] My secrets - Parsing a "Masterseed" type is not working

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#34]
When creating a new seedphrase using the old Seedkeeper application, a masterseed is also created. 
Currently, in this app, the masterseed is not shown properly.

Look here, ID 14 is my BIP39 seedphrase (please see issue #27) and ID 15 is the corresponding masterseed.
![image](https://github.com/user-attachments/assets/dcaa2245-a6e1-4f9c-a8ad-596c5ae594e7)

If I click on the ID 15, I can't see the masterseed
![image](https://github.com/user-attachments/assets/bd2f1de1-6998-4192-b4a7-f92384d6e6b4)

**Comment by Tech-Aware** [comment]
I think it's because i only work with 12 and 24 words mnemonic, i will also add this !
