### ISSUE TITLE
[UI-Update] My Secrets - Secret details fir a masterseed - Xpub and SeedQR button should be removed

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#35]
On the "My Secrets" - "Secrets details", for a masterseed secret, you present those options: 
- xpub
- seedqr

These options should not be present here... 
You can remove them.
The "SeedQR" button should only be available when the secret type is "Mnemonic seedphrase".

![image](https://github.com/user-attachments/assets/97220cc5-9482-437d-a87c-58dcff481af6)

**Comment by Tech-Aware** [comment]
@Bastien-Satochip

Here you have the commit https://github.com/Tech-Aware/seedkeeper-tool/commit/e75b9b1f1a9c9c84c7f912445de0b61e264bb665, https://github.com/Tech-Aware/seedkeeper-tool/commit/da782ddcec99ae7ee4b7d1dbc5c0a7a1ad8e3b73

https://github.com/user-attachments/assets/927bd5d5-93e4-41e7-a91b-efa51e4574e1

**Comment by Bastien-Satochip** [comment]
Perfect, thank you.
