### ISSUE TITLE
[UI-Update] My Secrets - Secret details - Add the SeedQR button for mnemonic seedphrase

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#36]
You first have to cover the issues #27 and #35 before this one.
When you select a mnemonic seedphrase from "My Secrets", you should be able to display it as a SeedQR format.

**Comment by Tech-Aware** [comment]
@Bastien-Satochip 

Here you have the commit  e75b9b1f1a9c9c84c7f912445de0b61e264bb665, da782ddcec99ae7ee4b7d1dbc5c0a7a1ad8e3b73

Here you have an example in app :
https://github.com/user-attachments/assets/d208599b-220a-40f1-acfd-a8130b468624

**Comment by Bastien-Satochip** [comment]
All good.
