### ISSUE TITLE
[UX-update] When a card is removed, update the UI

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#39]
With the latest release, when I remove a card, the app still show the secrets screen. 
It's quite a bit confusing for the user. 

Could you make the app go to the home screen (asking to plug a card) when a card is removed?

**Comment by Tech-Aware** [comment]
@Bastien-Satochip 
I can do it but when we will be inside backup process, could interfere with the process exiting user from backu process frames

**Comment by Bastien-Satochip** [comment]
All good, thank you.
