### ISSUE TITLE
[UX-Update] Create a back button in the menu when you are in the Settings

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#4]
I like the Setting button and the menu update... 
But it takes me a few seconds to realize how to go back to the first menu... 
If you are on the "About" screen and want to go back to the Seedkeeper-Tool menu, you need to click on "Back" and again click on "Back" from the home screen. 

How about adding a "Back" button (with an arrow symbol <-) inside the Settings menu... 
You can optionnaly remove the "Go to the webshop" button and in this place, put the "Back" button. 

![image](https://github.com/user-attachments/assets/b4867d97-f213-4fad-b90f-0378547d7e6f)

This screen ask the user to click on the menu to do an action... But on the menu, there is no "back" button to go back to the "Seedkeeper-tool" menu.
![image](https://github.com/user-attachments/assets/8326cd4c-f05b-487f-9bb1-6e4a8bf25f21)

**Comment by Tech-Aware** [comment]
Here you have @Bastien-Satochip 
3fe50d312adcfe60bd356f6c5de6f501c4a61c69
