### ISSUE TITLE
[Bug] The "SeedQR" qr code is not well encoded.

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#42]
There is still a problem with the SeedQR code button. 

The QR code generated is not well encoded. 

Here is an example:

This seedphrase: taxi betray purity school install water feel tray kit fat balance march
With the passphrase: pass

Is encoded like this with the QR code: 
**b'taxi betray purity school install water feel tray kit fat balance march 'b' pass'**

![image](https://github.com/user-attachments/assets/049d43bd-523c-4d33-a0f5-6471756a9d9d)

**Comment by Tech-Aware** [comment]
here you have @Bastien-Satochip 
c4e9a7acbf311dc8e6323ad7bfd2833b1ab04aa7

Scan it to test if the result is good for you:
![image](https://github.com/user-attachments/assets/be215802-0094-46ec-8810-2ab51fb6d1be)

**Comment by Bastien-Satochip** [comment]
Works well. Thank you.
