### ISSUE TITLE
[UI-Update] Make the popup message more clear.

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#5]
When a user try to import a mnemonic seedphrase, if he selects 24-words and past a 12 words seedphrase, the pop up says:
"Failed to import seed".

First: make this pop up in the same look and feel like the others. With a logo a the same typo.

Second: if possible, explain why it failed. Maybe something like: Failed to import seed. Wrong size.
I don't know if this pop up is generic (no matter the size or the BIP39 checksum)...

![image](https://github.com/user-attachments/assets/d11c2197-9969-465e-86ef-538cd95bdf92)

**Comment by Tech-Aware** [comment]
And here you have @Bastien-Satochip 
8252847db6fa78c0c96f450b26d7409f223560a7
60b1be91ad265a7c140d7159bfa17f9b8ceb74b1
