### ISSUE TITLE
[UI-Update] Allow the user to see the passphrase 

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#7]
Generate or Import a seedphrase: the user should be able to see the passphrase. At least to avoid any mistake.

![image](https://github.com/user-attachments/assets/87cb3046-b654-4a7c-aeb0-035b6b19bd26)

I like the idea of the stars... But you should allow the user to click on a "eye" icon to see the passphrase he entered.

**Comment by Tech-Aware** [comment]
Here you have @Bastien-Satochip 
947188de097b7076e0913b08e04e3e92c3dfa894
