### ISSUE TITLE
[BUG] Cannot import a login/password

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/seedkeeper-tool#8]
The import of a login/password is not possible at all. 
When I hit the Save on card button, nothing appears. No logs, no pup up... I guess this functionnality is not working.

![image](https://github.com/user-attachments/assets/a998a48d-4883-4191-b769-17b821d27e3c)

**Comment by Tech-Aware** [comment]
Hey @Bastien-Satochip
It was a little bit gymnastic but i did it espicifically for password encryption and decryption
2f5b76a14aabc91de848f0e5edffbe3c78d23125
a68397039b0e47310945c2ecac733248c5da8807
